"""Turn aggregated sales metrics into a narrative business analysis.

With an Anthropic API key configured, the analysis is generated by Claude.
Without a key (or if the call fails) a built-in heuristic is used, so the
endpoint always returns something useful and the app runs out of the box.
"""

import json
import logging

from src.config import Config

from .schemas import Insight, InsightReport, SalesMetrics

logger = logging.getLogger("sales_insight.ai")

SYSTEM_PROMPT = """\
You are a senior sales analyst. You are given aggregated sales metrics as JSON.
Analyze them and respond with a concise, decision-useful assessment.

Respond with ONLY a JSON object (no markdown, no code fences) of the shape:
{
  "summary": "<2-4 sentence executive summary in plain language>",
  "key_findings": [
    {"title": "<short label>", "detail": "<one specific, data-grounded finding>"}
  ],
  "recommendations": ["<concrete, actionable recommendation>", ...]
}

Rules:
- Ground every statement in the numbers provided; never invent data.
- Prefer specific figures (revenue, units, region names) over vague claims.
- Provide 3-5 key findings and 3-5 recommendations.
"""


async def generate_insights(metrics: SalesMetrics) -> InsightReport:
    """Produce an InsightReport from the given metrics."""
    if not Config.ai_enabled:
        logger.info("No ANTHROPIC_API_KEY set — using heuristic insights.")
        return _heuristic_report(metrics)

    try:
        return await _ai_report(metrics)
    except Exception:  # noqa: BLE001 — never let AI failure break the endpoint
        logger.exception("AI insight generation failed — using heuristic fallback.")
        return _heuristic_report(metrics)


async def _ai_report(metrics: SalesMetrics) -> InsightReport:
    """Call Claude and parse its response into an InsightReport."""
    import anthropic

    client = anthropic.AsyncAnthropic(api_key=Config.ANTHROPIC_API_KEY)

    response = await client.messages.create(
        model=Config.ANTHROPIC_MODEL,
        max_tokens=2000,
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": f"Here are the sales metrics:\n{metrics.model_dump_json(indent=2)}",
            }
        ],
    )

    text = "".join(block.text for block in response.content if block.type == "text")
    data = _parse_json(text)

    return InsightReport(
        summary=(data.get("summary") or "").strip() or "No summary produced.",
        key_findings=[
            Insight(title=f.get("title", "Finding"), detail=f.get("detail", ""))
            for f in data.get("key_findings", [])
            if isinstance(f, dict)
        ],
        recommendations=[str(r) for r in data.get("recommendations", [])],
        source="ai",
        metrics=metrics,
    )


def _parse_json(text: str) -> dict:
    """Parse a JSON object out of the model's text, tolerating code fences."""
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        start, end = text.find("{"), text.rfind("}")
        if start != -1 and end != -1 and end > start:
            return json.loads(text[start : end + 1])
        raise


def _heuristic_report(metrics: SalesMetrics) -> InsightReport:
    """Rule-based analysis used when the AI model is unavailable."""
    findings: list[Insight] = []
    recommendations: list[str] = []

    if metrics.total_orders == 0:
        return InsightReport(
            summary="There is no sales data yet. Record some sales to unlock analysis.",
            key_findings=[],
            recommendations=["Add products, customers, and sales, then retry."],
            source="heuristic",
            metrics=metrics,
        )

    summary = (
        f"Across {metrics.total_orders} orders the business generated "
        f"${metrics.total_revenue:,.2f} in revenue "
        f"({metrics.total_units} units, ${metrics.average_order_value:,.2f} "
        f"average order value)."
    )

    if metrics.top_products:
        best = metrics.top_products[0]
        share = (
            best.revenue / metrics.total_revenue * 100 if metrics.total_revenue else 0
        )
        findings.append(
            Insight(
                title="Best-selling product",
                detail=f"'{best.name}' leads with ${best.revenue:,.2f} "
                f"({share:.0f}% of total revenue).",
            )
        )
        if share > 40:
            recommendations.append(
                f"Revenue is concentrated in '{best.name}'. Diversify the catalog "
                "to reduce dependence on a single product."
            )

    if metrics.top_categories:
        cat = metrics.top_categories[0]
        findings.append(
            Insight(
                title="Leading category",
                detail=f"'{cat.name}' is the top category at ${cat.revenue:,.2f}.",
            )
        )

    if metrics.revenue_by_region:
        top_region = metrics.revenue_by_region[0]
        findings.append(
            Insight(
                title="Strongest region",
                detail=f"'{top_region.name}' contributes the most revenue "
                f"(${top_region.revenue:,.2f}).",
            )
        )
        if len(metrics.revenue_by_region) > 1:
            weakest = metrics.revenue_by_region[-1]
            recommendations.append(
                f"'{weakest.name}' is the weakest region (${weakest.revenue:,.2f}). "
                "Consider targeted campaigns there."
            )

    if len(metrics.revenue_by_month) >= 2:
        months = list(metrics.revenue_by_month.items())
        first, last = months[0], months[-1]
        direction = "up" if last[1] >= first[1] else "down"
        findings.append(
            Insight(
                title="Revenue trend",
                detail=f"Monthly revenue moved {direction} from ${first[1]:,.2f} "
                f"({first[0]}) to ${last[1]:,.2f} ({last[0]}).",
            )
        )

    recommendations.append(
        "Focus retention on top customers — they drive a large share of revenue."
    )

    return InsightReport(
        summary=summary,
        key_findings=findings,
        recommendations=recommendations,
        source="heuristic",
        metrics=metrics,
    )
