"""Schemas for aggregated metrics, AI insight reports, and the dashboard."""

import uuid

from pydantic import BaseModel, Field


class TopItem(BaseModel):
    """A ranked entity (product, category, region, or customer)."""

    name: str
    revenue: float
    units: int


class EmployeeStat(BaseModel):
    """Operational metrics for one employee who recorded sales."""

    user_uid: uuid.UUID | None = None
    name: str
    email: str | None = None
    sales_count: int
    revenue: float


class SalesMetrics(BaseModel):
    """Aggregated numbers computed from one business's sales.

    Returned by `/insights/metrics` and fed to the AI model as the factual
    basis for its analysis. Always scoped to a single business.
    """

    total_revenue: float = 0.0
    total_orders: int = 0
    total_units: int = 0
    average_order_value: float = 0.0
    top_products: list[TopItem] = Field(default_factory=list)
    top_categories: list[TopItem] = Field(default_factory=list)
    revenue_by_region: list[TopItem] = Field(default_factory=list)
    top_customers: list[TopItem] = Field(default_factory=list)
    revenue_by_month: dict[str, float] = Field(default_factory=dict)
    sales_by_employee: list[EmployeeStat] = Field(default_factory=list)


class Insight(BaseModel):
    """A single, discrete finding."""

    title: str
    detail: str


class InsightReport(BaseModel):
    """The full analysis returned by `/insights/analyze`."""

    summary: str
    key_findings: list[Insight] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)
    source: str = Field(
        description="'ai' when generated by Claude, 'heuristic' when the "
        "built-in fallback was used (no API key configured)."
    )
    metrics: SalesMetrics


# --- Dashboard -----------------------------------------------------------
class DashboardBusiness(BaseModel):
    uid: uuid.UUID
    name: str


class DashboardMetrics(BaseModel):
    total_revenue: float = 0.0
    total_sales: int = 0
    products: int = 0
    customers: int = 0
    employees: int = 0


class MonthlyRevenuePoint(BaseModel):
    month: str
    revenue: float


class DashboardModel(BaseModel):
    business: DashboardBusiness
    metrics: DashboardMetrics
    top_products: list[TopItem] = Field(default_factory=list)
    top_customers: list[TopItem] = Field(default_factory=list)
    employee_sales: list[EmployeeStat] = Field(default_factory=list)
    monthly_revenue: list[MonthlyRevenuePoint] = Field(default_factory=list)
