"""Schemas for aggregated metrics and AI-generated insight reports."""

from pydantic import BaseModel, Field


class TopItem(BaseModel):
    """A ranked entity (product, category, region, or customer)."""

    name: str
    revenue: float
    units: int


class SalesMetrics(BaseModel):
    """Aggregated numbers computed from the sales table.

    Returned by `/insights/metrics` and fed to the AI model as the factual
    basis for its analysis.
    """

    total_revenue: float = 0.0
    total_orders: int = 0
    total_units: int = 0
    average_order_value: float = 0.0
    top_products: list[TopItem] = Field(default_factory=list)
    top_categories: list[TopItem] = Field(default_factory=list)
    revenue_by_region: list[TopItem] = Field(default_factory=list)
    top_customers: list[TopItem] = Field(default_factory=list)
    revenue_by_month: dict[str, float] = Field(default_factory=dict)


class Insight(BaseModel):
    """A single, discrete finding."""

    title: str
    detail: str


class InsightReport(BaseModel):
    """The full analysis returned by `/insights/analyze`."""

    summary: str
    key_findings: list[Insight] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)
    source: str = Field(
        description="'ai' when generated by Claude, 'heuristic' when the "
        "built-in fallback was used (no API key configured)."
    )
    metrics: SalesMetrics
